name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'  
  workflow_dispatch:  # This allows manual runs

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies and Run Linting
        run: |
          cd starter/backend
          sudo -H pip install -U pipenv
          pipenv install flask flake8
          pipenv run lint
        continue-on-error: false

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies and Run Tests
        run: |
          cd starter/backend
          sudo -H pip install -U pipenv
          pipenv install flask flake8
          pipenv run test  # Adjust this to the actual test command if needed
        continue-on-error: false

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd.io
          sudo apt-get install -y docker.io
          sudo service docker start
          sudo usermod -a -G docker $USER
        continue-on-error: false

      - name: Build Docker Image
        run: |
          cd starter/backend
          docker build --tag mp-backend:latest .

        continue-on-error: false