name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies and Run Linting
        run: |
          # Add commands to install dependencies and run linting for the backend here
          # Example:
          # npm ci
          # npm run lint

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies and Run Tests
        run: |
          # Add commands to install dependencies and run tests for the backend here
          # Example:
          # npm ci
          # npm test

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          # Add commands to build the Docker image for the backend here
          # Example:
          # docker build -t backend:latest .

  ecr-login:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

  ecr-push:
    runs-on: ubuntu-latest
    needs: ecr-login

    steps:
      - name: Push Docker Image to ECR
        run: |
          # Add commands to tag and push the Docker image to ECR here
          # Example:
          # docker tag backend:${{ github.sha }} <your-ecr-repository-url>:${{ github.sha }}
          # docker push <your-ecr-repository-url>:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - ecr-push

    steps:
      - name: Deploy to Kubernetes
        run: |
          # Add commands to deploy the application using kubectl here
          # Example:
          # kubectl apply -f kubernetes-manifests/backend-deployment.yaml
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml